# Uncomment the next line to define a global platform for your project
platform :ios, ‘10.0’
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'LYAutoUtilsTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYAutoUtils
  pod 'LYAutoUtils', :path=>'../'

end
